backport: allow empty commits
It's possible that the backport fails with the following, and in that case,
using allow-empty should fix the issue.

mergify_engine.utils: calling: cherry-pick -x fbe45bc808e752681cd6ff5717c8af73fdaebb8b
mergify_engine.utils: calling: status
mergify_engine.utils: calling: add *
mergify_engine.utils: calling: commit -a --no-edit
mergify_engine.utils: calling: cherry-pick -x 9e2213e309017842ad0939d4058ab04820334b94
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
mergify_engine.utils: calling: status
mergify_engine.utils: calling: add *
mergify_engine.utils: calling: commit -a --no-edit
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'

mergify_engine.backports [branch: stable/backport-foo] [pull_request: foo/bar/pull/334@develop s:merged]: backport failed
Traceback (most recent call last):
  File "/data/web_www/gh.mergify.io/src/mergify_engine/backports.py", line 147, in backport
    git("cherry-pick", "-x", commit.sha)
  File "/data/web_www/gh.mergify.io/src/mergify_engine/utils.py", line 210, in __call__
    return subprocess.check_output(["git"] + list(args), **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'cherry-pick', '-x', '9e2213e309017842ad0939d4058ab04820334b94']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/web_www/gh.mergify.io/src/mergify_engine/backports.py", line 152, in backport
    git("commit", "-a", "--no-edit")
  File "/data/web_www/gh.mergify.io/src/mergify_engine/utils.py", line 210, in __call__
    return subprocess.check_output(["git"] + list(args), **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '--no-edit']' returned non-zero exit status 1